/**
 * Writes a small synthetic pack, for pointing the engine demo at.
 *
 *   npm run sample:pack
 *
 * Synthetic on purpose. A pack cut from real data would prove the builder works, which
 * is not in question — what this is for is proving the *engine* can render a pack it
 * has never seen, produced by something that is not the builder. This script imports
 * core and nothing else: no DEM fetch, no Overpass, no browser.
 *
 * The island is a couple of radial falloffs with ridge noise on top, plus a coast at
 * zero so the water plane has something to do, and a road that runs from the shore
 * over the saddle so the vector path is visibly draped on relief rather than flat.
 */
import { writeFileSync } from 'node:fs'
import {
  buildPack,
  packToBytes,
  type HeightField,
  type PackInputLayer,
  type PackVectors,
} from '../src/index'

const W = 768
const H = 768

// A cheap value-noise field: deterministic, no dependency, good enough for relief.
function hash(x: number, y: number): number {
  const n = Math.sin(x * 127.1 + y * 311.7) * 43758.5453
  return n - Math.floor(n)
}
function smoothNoise(x: number, y: number): number {
  const xi = Math.floor(x)
  const yi = Math.floor(y)
  const xf = x - xi
  const yf = y - yi
  const u = xf * xf * (3 - 2 * xf)
  const v = yf * yf * (3 - 2 * yf)
  const a = hash(xi, yi)
  const b = hash(xi + 1, yi)
  const c = hash(xi, yi + 1)
  const d = hash(xi + 1, yi + 1)
  return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v
}
function fbm(x: number, y: number, octaves: number): number {
  let sum = 0
  let amp = 0.5
  let freq = 1
  for (let i = 0; i < octaves; i++) {
    sum += smoothNoise(x * freq, y * freq) * amp
    freq *= 2
    amp *= 0.5
  }
  return sum
}

const data = new Float32Array(W * H)
let min = Infinity
let max = -Infinity

for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    const nx = x / W
    const ny = y / H

    // Two peaks and a saddle between them.
    const d1 = Math.hypot(nx - 0.38, ny - 0.42)
    const d2 = Math.hypot(nx - 0.66, ny - 0.61)
    const cone = Math.max(0, 1 - d1 / 0.34) ** 1.7 * 1650 + Math.max(0, 1 - d2 / 0.26) ** 1.8 * 1150

    // Ridged noise, scaled down toward the coast so the shoreline stays legible.
    const ridge = (1 - Math.abs(fbm(nx * 7, ny * 7, 5) * 2 - 1)) ** 2
    const inland = Math.max(0, 1 - Math.min(d1, d2) / 0.5)
    const relief = ridge * 420 * inland + fbm(nx * 14, ny * 14, 4) * 90 * inland

    // Sea floor outside the island, so there is bathymetry rather than a hard edge.
    const shelf = Math.max(0, Math.min(d1, d2) - 0.44) * -900

    const h = cone + relief + shelf - 60
    data[y * W + x] = h
    if (h < min) min = h
    if (h > max) max = h
  }
}

const hf: HeightField = {
  width: W,
  height: H,
  data,
  bounds: { south: 19.32, north: 19.68, west: -155.42, east: -155.04 },
  min,
  max,
  demtype: 'SYNTHETIC',
  voids: 0,
}

// A derived-looking hydrology field, at its own coarser resolution — the same shape
// the builder's routing pass produces, and a check that off-grid layers survive.
const RW = W >> 1
const RH = H >> 1
const water = new Uint8Array(RW * RH * 4)
for (let y = 0; y < RH; y++) {
  for (let x = 0; x < RW; x++) {
    const h = data[y * 2 * W + x * 2]!
    const o = (y * RW + x) * 4
    const wet = h < 0 ? 255 : 0
    water[o] = wet // coverage
    water[o + 1] = 0 // lake flag
    water[o + 2] = wet ? 200 : 0 // log drainage
    water[o + 3] = 255
  }
}
const layers: PackInputLayer[] = [
  {
    id: 'water',
    data: water,
    channels: 4,
    width: RW,
    height: RH,
    description: 'Derived hydrology: coverage, lake flag, log drainage.',
  },
]

// A road from the south-west shore, over the saddle, to the north-east shore. Points
// are normalised box coordinates: x east, y south.
const road: number[] = []
for (let i = 0; i <= 60; i++) {
  const t = i / 60
  road.push(0.12 + t * 0.76, 0.86 - t * 0.7 + Math.sin(t * Math.PI * 2) * 0.05)
}
const coast: number[] = []
for (let i = 0; i <= 48; i++) {
  const a = (i / 48) * Math.PI * 2
  coast.push(0.5 + Math.cos(a) * 0.46, 0.5 + Math.sin(a) * 0.46)
}

const vectors: PackVectors = {
  roads: [
    { cls: 'primary', pts: Float32Array.from(road) },
    { cls: 'minor', pts: Float32Array.from(coast) },
  ],
  areas: [],
  places: [
    { kind: 'town', name: 'Landing', x: 0.14, y: 0.84 },
    { kind: 'peak', name: 'North Summit', x: 0.38, y: 0.42, elevation: Math.round(max) },
  ],
}

const files = buildPack({
  id: 'sample-island',
  name: 'Sample Island',
  description: 'Synthetic terrain, written by core alone — no DEM, no Overpass, no browser.',
  heights: hf,
  layers,
  vectors,
  attribution: [
    { source: 'Synthetic — generated by samplepack.ts', licence: 'MIT', covers: ['elevation', 'roads', 'places'] },
  ],
  generator: 'groundwork samplepack',
  createdAt: '2026-07-29T00:00:00.000Z',
})

const out = process.argv[2] ?? 'public/sample.gwpack'
const bytes = await packToBytes(files)
writeFileSync(out, bytes)
console.log(
  `wrote ${out} — ${(bytes.length / 1024).toFixed(0)} KB, ` +
    `${W}×${H}, ${Math.round(min)}–${Math.round(max)} m`,
)
